Add Server Side Encryption
ember-cli-deploy/ember-cli-deploy-s3-index pull request #67
Opened 2016-09-30 21:56 UTC by sethpollack

## What Changed & Why
Added an optional param `serverSideEncryption`.

## PR Checklist
- [x ] Add tests - just passed them.
- [x ] Add documentation

2016-10-03 09:50 UTC, LevelbossMike commented
I just restarted the Travis build and this LGTM. I'll merge this as soon as the build passes. Just out of curiosity what's the reason behind using server side encryption for index.html files? Company policy or real safety reasons?

2016-10-03 09:59 UTC, LevelbossMike commented
@sethpollack as the documentation states that there are only two supported values for the serverside-encryption key and we are asserting on passing `undefined` as a value (which seems to be unsupported as a value for the encryption key) I would actually as a safety measure like to see the tests be changed and filter out the serverside-encryption key for the s3-client if the user does not specify it. 

Did you check that the plugin still functions as expected without this option present for users that don't need this?

2016-10-03 10:03 UTC, LevelbossMike requested changes

2016-10-03 10:03 UTC, LevelbossMike commented on lib/s3.js
> +    if (serverSideEncryption) {
can we please add a test for this conditional

2016-10-05 04:11 UTC, sethpollack commented
Just a company policy. Do these changes help?

2016-10-05 04:50 UTC, LevelbossMike commented
@sethpollack tests are failing. I suggest we add two tests to the s3 client to make sure we are only adding this when the serverSideEncryption option is passed (one for not passing one for passing). And the same to index-nodetest.

2016-10-05 14:16 UTC, sethpollack commented
Oh oops. Git added it back to the options. This should fix it. 

I'll add the tests now.

2016-10-05 16:00 UTC, sethpollack commented
Actually, I need to add this to the activate hook too. 

Will push up the changes soon.

2016-10-09 09:09 UTC, LevelbossMike approved these changes

2016-10-09 09:10 UTC, merged

2016-10-09 09:11 UTC, LevelbossMike commented
:tada: thank you so much for this contribution @sethpollack